version: '3.1'

services:

  wordpress:
    container_name: drupal
    image: docker.io/library/drupal:latest
    restart: always
    depends_on: db
    ports:
      - 8082:80
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_USER: exampleuser
      DRUPAL_DB_PASSWORD: examplepass
      DRUPAL_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  db:
    container_name: drupaldb
    image: docker.io/library/mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
