version: '3.7'
services:
  dashboard:
    build: 
      context: ./
    container_name: visualizador_iip_2023
    restart: always
    ports:
      - 4284:8080
    networks:
      - network 
  
networks:
  network:
    driver: bridge